micronaut:
  application:
    name: pixOt6
datasources:
  default:
    url: ${DB_URI:`jdbc:postgresql://localhost:5433/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    schema-generate: CREATE_DROP
    dialect: POSTGRES

logger:
  levels:
    io.micronaut.transaction: DEBUG

jpa.default.properties.hibernate.bhm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true
jpa.default.properties.hibernate.bytecode.provider: none

http:
  services:
    ERP:
      url: ${ITAU_URL:`http://localhost:9091/api/v1/`}
    BCB:
      url: ${BCB_URL:`http://localhost:8082/api/v1/pix/keys/`}